export enum PartOfSpeech {
    NOUN = "NOUN",
    VERB = "VERB",
    ADJECTIVE = "ADJECTIVE",
    ADVERB = "ADVERB",
    PRONOUN = "PRONOUN",
    PREPOSITION = "PREPOSITION",
    INTERJECTION = "INTERJECTION",
    CONJUNCTION = "CONJUNCTION",
    PROPER_NOUN = "PROPER_NOUN"
}
