export enum FileType {
    ANDROID = "android",
    IOS = "ios",
    GETTEXT = "gettext",
    HTML = "html",
    JAVA_PROPERTIES = "java_properties",
    XLIFF = "xliff",
    XML = "xml",
    JSON = "json",
    DOCX = "docx",
    PPTX = "pptx",
    XLSX = "xlsx",
    IDML = "idml",
    QT = "qt",
    RESX = "resx",
    PLAIN_TEXT = "plain_text",
    CSV = "csv",
    SRT = "srt",
    STRINGSDICT = "stringsdict",
    XLS = "xls",
    DOC = "doc",
    PPT = "ppt",
    PRES = "pres",
    MADCAP = "madcap",
    YAML = "yaml",
    MARKDOWN = "markdown"
}
