export enum PageCountStatus {
    NOT_AVAILABLE_UNSUPPORTED = "NOT_AVAILABLE_UNSUPPORTED",
    PROCESSING = "PROCESSING",
    AVAILABLE = "AVAILABLE",
    NOT_AVAILABLE_LEGACY = "NOT_AVAILABLE_LEGACY",
    NOT_AVAILABLE_PROCESSING_FAILED = "NOT_AVAILABLE_PROCESSING_FAILED"
}
