export enum IssueSubType {
    CLARIFICATION = "CLARIFICATION",
    MISSPELLING = "MISSPELLING",
    POOR_TRANSLATION = "POOR_TRANSLATION",
    DOES_NOT_FIT_SPACE = "DOES_NOT_FIT_SPACE",
    PLACEHOLDER_ISSUE = "PLACEHOLDER_ISSUE",
    REVIEW_TRANSLATION = "REVIEW_TRANSLATION",
    CUSTOM = "CUSTOM",
    MT_ERROR = "MT_ERROR"
}
