enum WorkflowStepType {
    AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION",
    ANALYSIS = "ANALYSIS",
    WORK_APPROVAL = "WORK_APPROVAL",
    TRANSLATION = "TRANSLATION",
    POST_TRANSLATION__EDIT = "POST_TRANSLATION__EDIT",
    POST_TRANSLATION__REVIEW = "POST_TRANSLATION__REVIEW",
    ADMIN_APPROVAL = "ADMIN_APPROVAL",
    PUBLISH = "PUBLISH",
    POST_TRANSLATION__MONOLINGUAL_REVIEW = "POST_TRANSLATION__MONOLINGUAL_REVIEW",
    POST_TRANSLATION__POST_MACHINE_REVISION = "POST_TRANSLATION__POST_MACHINE_REVISION",
    POST_TRANSLATION__POST_MACHINE_REVISION_PRO = "POST_TRANSLATION__POST_MACHINE_REVISION_PRO"
}

export { WorkflowStepType };
